<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Tournament - Badminton Tournament Management</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-white" x-data="{
    categoryCount: 0,
    numberOfCourts: 1,
    categories: [],
    bracketType: 'single_elimination',
    
    calculateMatchesForBracket(slots, bracketType) {
        if (bracketType === 'single_elimination') {
            return slots - 1;
        } else if (bracketType === 'round_robin') {
            return (slots * (slots - 1)) / 2;
        }
        return slots - 1;
    },
    
    calculateRoundsForBracket(slots, bracketType) {
        const rounds = [];
        
        if (bracketType === 'single_elimination') {
            const numRounds = Math.ceil(Math.log2(slots));
            let remainingMatches = slots;
            const roundNames = ['Round 1', 'Round of 16', 'Quarterfinals', 'Semifinals', 'Finals'];
            
            for (let i = 0; i < numRounds; i++) {
                const matchesInRound = Math.ceil(remainingMatches / 2);
                const roundName = roundNames[i] || 'Round ' + (i + 1);
                
                rounds.push({
                    name: roundName,
                    matches: matchesInRound,
                });
                
                remainingMatches = matchesInRound;
            }
        } else { // round_robin
            const numRounds = slots - 1;
            const matchesPerRound = Math.floor(slots / 2);
            
            for (let i = 0; i < numRounds; i++) {
                rounds.push({
                    name: 'Round ' + (i + 1),
                    matches: matchesPerRound,
                });
            }
        }
        
        return rounds;
    },
    
    autoGenerateSchedulesForCategory(categoryIndex) {
        const category = this.categories[categoryIndex];
        if (!category) return;
        
        const slots = parseInt(category.slots) || 12;
        const rounds = this.calculateRoundsForBracket(slots, this.bracketType);
        
        // Get start date from form
        const startDateInput = document.querySelector('input[name=start_date]');
        const startDate = startDateInput ? startDateInput.value : '';
        
        if (!startDate) {
            // If no start date, don't generate schedules yet
            return;
        }
        
        // Remove existing schedules for this category
        this.schedules = this.schedules.filter(s => s.categoryIndex !== categoryIndex);
        
        // Generate schedules for each round
        let currentDate = startDate;
        let currentTime = '08:00';
        let courtNumber = 1;
        
        rounds.forEach((roundInfo, roundIndex) => {
            const matchesInRound = roundInfo.matches;
            const roundName = roundInfo.name;
            
            for (let i = 0; i < matchesInRound; i++) {
                this.schedules.push({
                    id: Date.now() + Math.random(),
                    categoryIndex: categoryIndex,
                    round: roundName,
                    roundNumber: roundIndex + 1,
                    court: courtNumber,
                    date: currentDate,
                    time: currentTime,
                    isAutoGenerated: true
                });
                
                // Increment court (round-robin through available courts)
                courtNumber = (courtNumber % this.numberOfCourts) + 1;
                
                // Increment time (45 minutes per match)
                const timeParts = currentTime.split(':');
                let hours = parseInt(timeParts[0]);
                let minutes = parseInt(timeParts[1]);
                minutes += 45;
                if (minutes >= 60) {
                    hours += 1;
                    minutes = 0;
                }
                if (hours >= 20) { // End of day, move to next day
                    const dateObj = new Date(currentDate);
                    dateObj.setDate(dateObj.getDate() + 1);
                    currentDate = dateObj.toISOString().split('T')[0];
                    hours = 8;
                    minutes = 0;
                }
                currentTime = String(hours).padStart(2, '0') + ':' + String(minutes).padStart(2, '0');
            }
            
            // Move to next day after each round (except last round)
            if (roundIndex < rounds.length - 1) {
                const dateObj = new Date(currentDate);
                dateObj.setDate(dateObj.getDate() + 1);
                currentDate = dateObj.toISOString().split('T')[0];
                currentTime = '08:00';
            }
        });
        
        this.scheduleCount = this.schedules.length;
    },
    
    addCategory() {
        const newCategory = {
            id: Date.now(),
            type: '',
            slots: '',
            skill_level: '',
            age_bracket: '',
            schedule_start_time: '09:00',
            match_duration_minutes: 45,
            break_between_matches_minutes: 5
        };
        this.categories.push(newCategory);
        this.categoryCount = this.categories.length;
    },
    
    removeCategory(index) {
        this.categories.splice(index, 1);
        this.categoryCount = this.categories.length;
    },
    
    updateCategory(index) {
        const category = this.categories[index];
        if (!category) return;
        
        // Auto-set match duration based on category type
        if (category.type === 'MS' || category.type === 'WS') {
            category.match_duration_minutes = 45; // Singles: 45 minutes
        } else if (category.type === 'MD' || category.type === 'WD' || category.type === 'XD') {
            category.match_duration_minutes = 60; // Doubles/Mixed: 60 minutes
        }
    },
    
    getCourts() {
        const courts = [];
        for (let i = 1; i <= this.numberOfCourts; i++) {
            courts.push(i);
        }
        return courts;
    },
    
    updateCourts() {
        const courtsInput = document.querySelector('input[name=number_of_courts]');
        if (courtsInput) {
            this.numberOfCourts = parseInt(courtsInput.value) || 1;
            // No auto-generation in Create Tournament
        }
    },
    
    init() {
        // No autofill - start with empty categories
        
        // Watch for changes in number_of_courts
        this.$nextTick(() => {
            const courtsInput = document.querySelector('input[name=number_of_courts]');
            if (courtsInput) {
                this.numberOfCourts = parseInt(courtsInput.value) || 1;
                courtsInput.addEventListener('input', () => this.updateCourts());
            }
            
            // Watch for bracket type changes (no auto-generation in Create Tournament)
            const bracketTypeSelect = document.querySelector('select[name=bracket_type]');
            if (bracketTypeSelect) {
                const self = this;
                bracketTypeSelect.addEventListener('change', function(e) {
                    self.bracketType = e.target.value;
                    // No auto-generation - all schedules are manual
                });
            }
        });
    }
}">
    <div class="flex h-screen overflow-hidden">
        <!-- Sidebar -->
        @include('layouts.manager-sidebar')

        <!-- Main Content Area -->
        <div class="flex-1 flex flex-col overflow-hidden">
            <!-- Top Bar -->
            <header class="bg-white border-b border-gray-200 px-8 py-4">
                <div class="flex items-center">
                    <a href="/manager/tournaments" class="mr-4 text-gray-600 hover:text-gray-800">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                        </svg>
                    </a>
                    <h1 class="text-2xl font-bold text-black">Create Tournament</h1>
                </div>
            </header>

            <!-- Main Content -->
            <main class="flex-1 overflow-y-auto bg-gray-50 p-8">
                @if(!$canCreateTournament)
                    <!-- Insufficient Players Message -->
                    <div class="max-w-4xl mx-auto">
                        <div class="bg-yellow-50 border-l-4 border-yellow-400 p-6 rounded-lg shadow-sm">
                            <div class="flex items-start">
                                <div class="flex-shrink-0">
                                    <svg class="h-6 w-6 text-yellow-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path>
                                    </svg>
                                </div>
                                <div class="ml-3 flex-1">
                                    <h3 class="text-lg font-semibold text-yellow-800 mb-2">Cannot Create Tournament</h3>
                                    <div class="text-sm text-yellow-700">
                                        <p class="mb-3">
                                            Your club must have at least <strong>5 active players</strong> before you can create a tournament.
                                        </p>
                                        <div class="bg-white rounded-md p-4 border border-yellow-200">
                                            <div class="flex items-center justify-between mb-2">
                                                <span class="font-medium text-gray-900">Current Active Players:</span>
                                                <span class="text-2xl font-bold {{ $activePlayersCount >= 5 ? 'text-green-600' : 'text-yellow-600' }}">
                                                    {{ $activePlayersCount }}
                                                </span>
                                            </div>
                                            <div class="mt-3 pt-3 border-t border-yellow-200">
                                                <p class="text-sm text-gray-600 mb-2">
                                                    <strong>Required:</strong> 5 active players
                                                </p>
                                                <div class="w-full bg-yellow-200 rounded-full h-2.5">
                                                    <div class="bg-yellow-600 h-2.5 rounded-full" style="width: {{ min(($activePlayersCount / 5) * 100, 100) }}%"></div>
                                                </div>
                                                <p class="text-xs text-gray-500 mt-2">
                                                    {{ max(0, 5 - $activePlayersCount) }} more player(s) needed
                                                </p>
                                            </div>
                                        </div>
                                        <div class="mt-4">
                                            <a href="{{ route('manager.club') }}" class="inline-flex items-center px-4 py-2 bg-[#2C5F4F] hover:bg-[#244D3E] text-white font-medium rounded-md transition duration-200">
                                                <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
                                                </svg>
                                                Go to My Club to Invite Players
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @else
                    <!-- Success/Error Messages -->
                    @if(session('success'))
                        <div class="mb-4 bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                            <span class="block sm:inline">{{ session('success') }}</span>
                        </div>
                    @endif
                    
                    @if(session('error'))
                        <div class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                            <span class="block sm:inline">{{ session('error') }}</span>
                        </div>
                    @endif
                    
                    @if($errors->any())
                        <div class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                            <strong class="font-bold">Please fix the following errors:</strong>
                            <ul class="list-disc list-inside mt-2">
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    
                    <!-- Tournament Creation Form -->
                    <form action="{{ route('manager.tournaments.store') }}" method="POST" enctype="multipart/form-data" class="max-w-4xl">
                        @csrf
                    <!-- Tournament Name -->
                    <div class="mb-6">
                        <label class="block text-base font-semibold text-black mb-2">Tournament Name</label>
                        <input type="text" name="name" placeholder="Enter tournament name" required class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                    </div>

                    <!-- Venue Row -->
                    <div class="mb-6">
                        <div class="grid grid-cols-2 gap-4">
                            <div>
                                <label class="block text-base font-semibold text-black mb-2">Venue</label>
                                <div class="relative">
                                    <input 
                                        type="text" 
                                        id="venue_name" 
                                        name="venue_name" 
                                        placeholder="Enter Venue (start typing for suggestions)" 
                                        required 
                                        autocomplete="off"
                                        class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]"
                                    >
                                    <!-- Autocomplete Dropdown -->
                                    <div id="venue-autocomplete" class="absolute z-50 w-full mt-1 bg-white border border-gray-300 rounded-md shadow-lg hidden max-h-60 overflow-y-auto">
                                        <!-- Suggestions will be inserted here -->
                                    </div>
                                </div>
                            </div>
                            <div>
                                <label class="block text-base font-semibold text-black mb-2"># of Courts</label>
                                <input type="number" name="number_of_courts" placeholder="Enter # of courts" required min="1" max="50" x-model="numberOfCourts" @input="updateCourts()" class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                            </div>
                        </div>
                    </div>

                    <!-- Dates Row -->
                    <div class="grid grid-cols-2 gap-4 mb-6">
                        <div>
                            <label class="block text-base font-semibold text-black mb-2">Start Date</label>
                            <input type="date" name="start_date" required class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                        </div>
                        <div>
                            <label class="block text-base font-semibold text-black mb-2">End Date</label>
                            <input type="date" name="end_date" required class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                        </div>
                    </div>

                    <!-- Deadlines Row -->
                    <div class="grid grid-cols-2 gap-4 mb-6">
                        <div>
                            <label class="block text-base font-semibold text-black mb-2">Registration Deadline</label>
                            <input type="date" name="registration_deadline" required class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                        </div>
                        <div>
                            <label class="block text-base font-semibold text-black mb-2">Withdrawal Deadline</label>
                            <input type="date" name="withdrawal_deadline" required class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                        </div>
                    </div>

                    <!-- Description -->
                    <div class="mb-6">
                        <label class="block text-base font-semibold text-black mb-2">Description / Overview</label>
                        <textarea name="description" rows="5" placeholder="Write a short overview of the tournament" class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]"></textarea>
                    </div>

                    <!-- Tournament Format -->
                    <div class="mb-6">
                        <label class="block text-base font-semibold text-black mb-2">Tournament Format</label>
                        <select name="bracket_type" x-model="bracketType" required class="w-full max-w-md px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                            <option value="single_elimination" selected>Single Elimination</option>
                            <option value="round_robin">Round Robin</option>
                        </select>
                        <p class="text-sm text-gray-600 mt-1">Select the tournament bracket format.</p>
                    </div>

                    <!-- Tournament Type -->
                    <div class="mb-6">
                        <label class="flex items-center">
                            <input type="checkbox" name="is_dual_meet" value="1" class="w-5 h-5 text-[#2C5F4F] border-gray-300 rounded focus:ring-[#2C5F4F]">
                            <span class="ml-2 text-base font-semibold text-black">Dual Meet Tournament</span>
                        </label>
                        <p class="text-sm text-gray-600 mt-1 ml-7">Check if this is a dual meet tournament between two clubs</p>
                    </div>

                    <!-- Category Section -->
                    <div class="mb-6">
                        <div class="flex justify-between items-center mb-4">
                            <label class="block text-base font-semibold text-black">Category</label>
                            <div class="flex items-center gap-3">
                                <span class="text-sm text-gray-500" x-text="categoryCount + ' added'"></span>
                                <button type="button" @click="addCategory()" class="bg-[#2C5F4F] hover:bg-[#244D3E] text-white px-4 py-2 rounded-md text-sm font-medium transition duration-200">
                                    + Add Category
                                </button>
                            </div>
                        </div>
                        <div class="bg-white border border-gray-300 rounded-md p-4 space-y-4">
                            <!-- Match Scheduling Instructions -->
                            <div class="bg-blue-50 border-l-4 border-blue-400 p-4 mb-4 rounded">
                                <div class="flex items-start">
                                    <svg class="h-5 w-5 text-blue-400 mt-0.5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                    </svg>
                                    <div>
                                        <h4 class="text-sm font-semibold text-blue-800 mb-2">Match Scheduling Guide</h4>
                                        <ul class="text-xs text-blue-700 space-y-1 list-disc list-inside">
                                            <li><strong>Multiple Categories:</strong> Categories can start at the same time (e.g., 9:00 AM). Courts will be split between categories automatically.</li>
                                            <li><strong>Round Schedule:</strong> Rounds are distributed evenly across tournament days. All rounds (including finals) use your category's start time.</li>
                                            <li><strong>Match Duration:</strong> Singles: 30-45 min, Doubles/Mixed: 45-60 min. Breaks only apply within matches (3 sets).</li>
                                            <li><strong>Court Allocation:</strong> If categories ≤ courts, all run simultaneously (courts split evenly). If categories > courts, categories are grouped into batches that run sequentially. Example: 4 courts, 2 categories → both run together. 3 courts, 4 categories → first 3 run together, then the 4th runs after.</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <template x-for="(category, index) in categories" :key="category.id">
                                <div class="border border-gray-200 rounded-lg p-4 space-y-3">
                                    <div class="grid grid-cols-5 gap-3 items-end">
                                        <select :name="'categories[' + index + '][type]'" x-model="category.type" @change="updateCategory(index)" required class="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                                            <option value="MS">Men's Singles</option>
                                            <option value="WS">Women's Singles</option>
                                            <option value="MD">Men's Doubles</option>
                                            <option value="WD">Women's Doubles</option>
                                            <option value="XD">Mixed Doubles</option>
                                        </select>
                                        <input type="number" :name="'categories[' + index + '][slots]'" x-model="category.slots" @change="updateCategory(index)" placeholder="Slots (min: 12)" required min="12" max="128" class="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                                        <select :name="'categories[' + index + '][skill_level_requirements]'" x-model="category.skill_level" required class="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                                            <option value="">Select Skill Level</option>
                                            <option value="A">Level A</option>
                                            <option value="B">Level B</option>
                                            <option value="C">Level C</option>
                                            <option value="D">Level D</option>
                                            <option value="Open">Open for Everyone</option>
                                        </select>
                                        <select :name="'categories[' + index + '][age_requirement]'" x-model="category.age_bracket" required class="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                                            <option value="">Select Age Bracket</option>
                                            <option value="Junior (13-16)">Junior (13-16)</option>
                                            <option value="Senior (17-35)">Senior (17-35)</option>
                                            <option value="Veteran (36-50)">Veteran (36-50)</option>
                                            <option value="Master (51+)">Master (51+)</option>
                                            <option value="Open">Open (All Ages)</option>
                                        </select>
                                        <button type="button" @click="removeCategory(index)" class="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-md text-sm font-medium transition duration-200">
                                            Remove
                                        </button>
                                    </div>
                                    <div class="grid grid-cols-3 gap-3 items-end">
                                        <div>
                                            <label class="block text-xs text-gray-600 mb-1">Category Start Time</label>
                                            <input type="time" :name="'categories[' + index + '][schedule_start_time]'" x-model="category.schedule_start_time" :value="category.schedule_start_time || '09:00'" required class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                                        </div>
                                        <div>
                                            <label class="block text-xs text-gray-600 mb-1">Match Duration (minutes)</label>
                                            <select :name="'categories[' + index + '][match_duration_minutes]'" x-model="category.match_duration_minutes" required class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                                                <option value="30">30 minutes</option>
                                                <option value="45">45 minutes</option>
                                                <option value="60">60 minutes</option>
                                                <option value="75">75 minutes</option>
                                            </select>
                                        </div>
                                        <div>
                                            <label class="block text-xs text-gray-600 mb-1">Break Between Matches (minutes)</label>
                                            <select :name="'categories[' + index + '][break_between_matches_minutes]'" x-model="category.break_between_matches_minutes" required class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                                                <option value="5">5 minutes</option>
                                                <option value="10">10 minutes</option>
                                                <option value="15">15 minutes</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </template>
                        </div>
                    </div>

                    <!-- Match Schedules Info -->
                    <div class="mb-6">
                        <div class="bg-blue-50 border-l-4 border-blue-400 p-4 rounded">
                            <div class="flex items-start">
                                <svg class="h-5 w-5 text-blue-400 mt-0.5 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                </svg>
                                <div>
                                    <h4 class="text-sm font-semibold text-blue-800 mb-1">Match Schedules</h4>
                                    <p class="text-sm text-blue-700">
                                        Match schedules will be <strong>automatically generated</strong> for each category based on the start time, match duration, and break settings you configure above. 
                                        When you generate matches for this tournament, all matches will be scheduled with specific dates, times, and court assignments based on your category configurations.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Tournament Fee -->
                    <div class="mb-6">
                        <label class="block text-base font-semibold text-black mb-2">Tournament Fee</label>
                        <input type="number" name="tournament_fee" placeholder="Enter fee (₱)" required min="0" step="0.01" class="w-full max-w-md px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                    </div>

                    <!-- Contact Information -->
                    <div class="mb-6">
                        <label class="block text-base font-semibold text-black mb-4">Contact Information</label>
                        <div class="grid grid-cols-2 gap-4 mb-4">
                            <input type="tel" name="contact_phone" placeholder="Phone" required class="px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                            <input type="email" name="contact_email" placeholder="Email" required class="px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-gray-700 mb-2">Messenger / Facebook Link (Optional)</label>
                            <input type="url" name="facebook_link" placeholder="https://facebook.com/managerusername" class="w-full px-4 py-3 border border-gray-300 rounded-md focus:outline-none focus:border-[#2C5F4F]">
                        </div>
                    </div>

                    <!-- Tournament Banner -->
                    <div class="mb-8">
                        <label class="block text-base font-semibold text-black mb-2">Tournament Banner / Logo</label>
                        <div class="border border-gray-300 rounded-md p-4 bg-white">
                            <input type="file" name="banner" accept="image/jpeg,image/jpg,image/png" class="w-full">
                        </div>
                    </div>

                    <!-- Action Buttons -->
                    <div class="flex justify-end gap-4">
                        <button type="button" class="bg-white border-2 border-gray-300 text-gray-700 px-8 py-3 rounded-md font-semibold hover:bg-gray-50 transition duration-200">
                            Save Draft
                        </button>
                        <button type="submit" class="bg-[#1B4965] hover:bg-[#143850] text-white px-8 py-3 rounded-md font-semibold transition duration-200">
                            Create & Post
                        </button>
                    </div>
                    </form>
                @endif
            </main>
        </div>
    </div>

    <script>
        // OpenStreetMap Nominatim Autocomplete for Venue
        (function() {
            const venueInput = document.getElementById('venue_name');
            const autocompleteDiv = document.getElementById('venue-autocomplete');
            let debounceTimer;
            let selectedIndex = -1;
            let suggestions = [];

            if (!venueInput || !autocompleteDiv) return;

            // Fetch suggestions from Nominatim
            async function fetchSuggestions(query) {
                if (query.length < 3) {
                    autocompleteDiv.classList.add('hidden');
                    return;
                }

                try {
                    // Use Nominatim Search API with Philippines focus
                    const url = `https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(query)}&countrycodes=ph&limit=5&addressdetails=1`;
                    
                    const response = await fetch(url, {
                        headers: {
                            'User-Agent': 'Badminton Tournament Management System'
                        }
                    });
                    
                    if (!response.ok) throw new Error('Failed to fetch suggestions');
                    
                    const data = await response.json();
                    suggestions = data;
                    displaySuggestions(data);
                } catch (error) {
                    console.error('Error fetching location suggestions:', error);
                    autocompleteDiv.classList.add('hidden');
                }
            }

            // Display suggestions in dropdown
            function displaySuggestions(results) {
                if (results.length === 0) {
                    autocompleteDiv.classList.add('hidden');
                    return;
                }

                autocompleteDiv.innerHTML = '';
                results.forEach((result, index) => {
                    const item = document.createElement('div');
                    item.className = 'px-4 py-3 hover:bg-gray-100 cursor-pointer border-b border-gray-200 last:border-b-0';
                    item.dataset.index = index;
                    
                    // Format display name
                    const displayName = result.display_name || result.name || 'Unknown location';
                    const shortName = displayName.split(',')[0] + (displayName.split(',')[1] ? ', ' + displayName.split(',')[1] : '');
                    
                    item.innerHTML = `
                        <div class="font-medium text-gray-900">${shortName}</div>
                        <div class="text-sm text-gray-500 mt-1">${displayName.length > 60 ? displayName.substring(0, 60) + '...' : displayName}</div>
                    `;
                    
                    item.addEventListener('click', () => selectSuggestion(result));
                    item.addEventListener('mouseenter', () => {
                        // Remove previous highlight
                        autocompleteDiv.querySelectorAll('.bg-gray-100').forEach(el => {
                            el.classList.remove('bg-gray-100');
                            el.classList.add('hover:bg-gray-100');
                        });
                        // Add highlight
                        item.classList.remove('hover:bg-gray-100');
                        item.classList.add('bg-gray-100');
                        selectedIndex = index;
                    });
                    
                    autocompleteDiv.appendChild(item);
                });
                
                autocompleteDiv.classList.remove('hidden');
                selectedIndex = -1;
            }

            // Select a suggestion
            function selectSuggestion(result) {
                venueInput.value = result.display_name || result.name;
                autocompleteDiv.classList.add('hidden');
                suggestions = [];
                
                // Store additional location data if needed (lat, lon, etc.)
                if (result.lat && result.lon) {
                    // You can store these in hidden fields if needed
                    const latInput = document.querySelector('input[name="venue_latitude"]');
                    const lonInput = document.querySelector('input[name="venue_longitude"]');
                    if (latInput) latInput.value = result.lat;
                    if (lonInput) lonInput.value = result.lon;
                }
            }

            // Handle input with debounce
            venueInput.addEventListener('input', (e) => {
                clearTimeout(debounceTimer);
                const query = e.target.value.trim();
                
                debounceTimer = setTimeout(() => {
                    fetchSuggestions(query);
                }, 300); // 300ms debounce
            });

            // Handle keyboard navigation
            venueInput.addEventListener('keydown', (e) => {
                if (!autocompleteDiv.classList.contains('hidden') && suggestions.length > 0) {
                    if (e.key === 'ArrowDown') {
                        e.preventDefault();
                        selectedIndex = Math.min(selectedIndex + 1, suggestions.length - 1);
                        highlightSuggestion(selectedIndex);
                    } else if (e.key === 'ArrowUp') {
                        e.preventDefault();
                        selectedIndex = Math.max(selectedIndex - 1, -1);
                        highlightSuggestion(selectedIndex);
                    } else if (e.key === 'Enter' && selectedIndex >= 0) {
                        e.preventDefault();
                        selectSuggestion(suggestions[selectedIndex]);
                    } else if (e.key === 'Escape') {
                        autocompleteDiv.classList.add('hidden');
                        selectedIndex = -1;
                    }
                }
            });

            // Highlight suggestion
            function highlightSuggestion(index) {
                const items = autocompleteDiv.querySelectorAll('[data-index]');
                items.forEach((item, i) => {
                    if (i === index) {
                        item.classList.remove('hover:bg-gray-100');
                        item.classList.add('bg-gray-100');
                    } else {
                        item.classList.remove('bg-gray-100');
                        item.classList.add('hover:bg-gray-100');
                    }
                });
            }

            // Close dropdown when clicking outside
            document.addEventListener('click', (e) => {
                if (!venueInput.contains(e.target) && !autocompleteDiv.contains(e.target)) {
                    autocompleteDiv.classList.add('hidden');
                }
            });

            // Close dropdown on blur (with delay to allow click events)
            venueInput.addEventListener('blur', () => {
                setTimeout(() => {
                    autocompleteDiv.classList.add('hidden');
                }, 200);
            });
        })();
    </script>
</body>
</html>
